/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-21 02:08:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.schoolMyPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class scDh_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/myPage/myPage.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/myPage/donationHistory.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../fix/header.jsp", out, false);
      out.write("\r\n");
      out.write("   <div id=\"myPage\">\r\n");
      out.write("      <!-- 마이페이지 패스워드 입력 -->\r\n");
      out.write("      <!-- 헤더쪽 -->\r\n");
      out.write("      <div id=\"title\">\r\n");
      out.write("         <div>\r\n");
      out.write("            마이페이지\r\n");
      out.write("            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"14\" height=\"14\"\r\n");
      out.write("               fill=\"none\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                        <path fill-rule=\"evenodd\"\r\n");
      out.write("                  d=\"M8.5 18.5l6-6.5-6-6.5L10 4l7.5 8-7.5 8-1.5-1.5z\" fill=\"#A2A2A2\"></path>\r\n");
      out.write("                    </svg>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"account\">milestone1001@gmail.com</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- 메뉴 -->\r\n");
      out.write("      <main>\r\n");
      out.write("         <div id=\"myPageMenu\">\r\n");
      out.write("            <div id=\"menus\">메뉴</div>\r\n");
      out.write("            <a>\r\n");
      out.write("               <div class=\"menu\"\r\n");
      out.write("                  onclick=\"location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/schoolMyPage/scModify.jsp'\">보육원\r\n");
      out.write("                  정보수정</div>\r\n");
      out.write("            </a> <a>\r\n");
      out.write("               <div class=\"menu\"\r\n");
      out.write("                  onclick=\"location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/schoolMyPage/scDh.jsp'\">기부\r\n");
      out.write("                  받은내역</div>\r\n");
      out.write("            </a> <a>\r\n");
      out.write("               <div class=\"menu\"\r\n");
      out.write("                  onclick=\"location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/schoolMyPage/sccalendar.jsp'\">보육원\r\n");
      out.write("                  활동일정</div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <!-- <a>\r\n");
      out.write("                    <div class=\"menu\">회원탈퇴</div>\r\n");
      out.write("                </a> -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- 내용  section : 여러개의 내용이들어갈 것 -->\r\n");
      out.write("         <section id=\"myPageSection\">\r\n");
      out.write("            <div id=\"adBanner\">\r\n");
      out.write("               <div id=\"adBox\">\r\n");
      out.write("                  <div id=\"texts\">\r\n");
      out.write("                     <p class=\"adText1\">\r\n");
      out.write("                        연장권 구매하고 싶은데<br>포인트가 부족하다면?\r\n");
      out.write("                     </p>\r\n");
      out.write("                     <p class=\"adText2\">101프라임 가입하고 무제한 수강하세요!</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div id=\"adImgBox\">\r\n");
      out.write("                     <img id=\"adImg\"\r\n");
      out.write("                        src=\"https://cdn.class101.net/images/ff8e2a46-501c-4f1c-a7be-76e658928397/640xauto.webp\">\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"donationHistory\">\r\n");
      out.write("               <div class=\"dhTitle\"\r\n");
      out.write("                  style=\"font-size: 18px; font-weight: bolder; color: rgb(26, 26, 26); line-height: 24px; letter-spacing: -0.45px;\">기부받은\r\n");
      out.write("                  내역</div>\r\n");
      out.write("               <div class=\"dhList\">\r\n");
      out.write("                  <img\r\n");
      out.write("                     src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp\">\r\n");
      out.write("                  <div id=\"left\">\r\n");
      out.write("                     <div>2022.10.01</div>\r\n");
      out.write("                     <div\r\n");
      out.write("                        style=\"color: rgb(253, 126, 20); font-size: 13px; font-weight: 600;\">김팀장</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div id=\"rightButton\">\r\n");
      out.write("                     1,000,000\r\n");
      out.write("                     <div id=\"won\">원</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"dhList\">\r\n");
      out.write("                  <img\r\n");
      out.write("                     src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp\">\r\n");
      out.write("                  <div id=\"left\">\r\n");
      out.write("                     <div>2022.10.01</div>\r\n");
      out.write("                     <div\r\n");
      out.write("                        style=\"color: rgb(253, 126, 20); font-size: 13px; font-weight: 600;\">부팀장짱</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div id=\"rightButton\">\r\n");
      out.write("                     1,000,000\r\n");
      out.write("                     <div id=\"won\">원</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"dhList\">\r\n");
      out.write("                  <img\r\n");
      out.write("                     src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp\">\r\n");
      out.write("                  <div id=\"left\">\r\n");
      out.write("                     <div>2022.10.01</div>\r\n");
      out.write("                     <div\r\n");
      out.write("                        style=\"color: rgb(253, 126, 20); font-size: 13px; font-weight: 600;\">황지수와아이들</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div id=\"rightButton\">든킨도나스</div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"dhList\">\r\n");
      out.write("                  <img\r\n");
      out.write("                     src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp\">\r\n");
      out.write("                  <div id=\"left\">\r\n");
      out.write("                     <div>2022.10.01</div>\r\n");
      out.write("                     <div\r\n");
      out.write("                        style=\"color: rgb(253, 126, 20); font-size: 13px; font-weight: 600;\">닉네임소재a</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div id=\"rightButton\">교촌치킨</div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"dhList\">\r\n");
      out.write("                  <img\r\n");
      out.write("                     src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp\">\r\n");
      out.write("                  <div id=\"left\">\r\n");
      out.write("                     <div>2022.10.01</div>\r\n");
      out.write("                     <div\r\n");
      out.write("                        style=\"color: rgb(253, 126, 20); font-size: 13px; font-weight: 600;\">떨어져간다123</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div id=\"rightButton\">베스킨라빈스</div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"dhList\">\r\n");
      out.write("                  <img\r\n");
      out.write("                     src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp\">\r\n");
      out.write("                  <div id=\"left\">\r\n");
      out.write("                     <div>2022.10.01</div>\r\n");
      out.write("                     <div\r\n");
      out.write("                        style=\"color: rgb(253, 126, 20); font-size: 13px; font-weight: 600;\">개발상팔</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div id=\"rightButton\">\r\n");
      out.write("                     3,000,000\r\n");
      out.write("                     <div id=\"won\">원</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"dhList\">\r\n");
      out.write("                  <img\r\n");
      out.write("                     src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp\">\r\n");
      out.write("                  <div id=\"left\">\r\n");
      out.write("                     <div>2022.10.01</div>\r\n");
      out.write("                     <div\r\n");
      out.write("                        style=\"color: rgb(253, 126, 20); font-size: 13px; font-weight: 600;\">4팀짱</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div id=\"rightButton\">\r\n");
      out.write("                     500,000\r\n");
      out.write("                     <div id=\"won\">원</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </section>\r\n");
      out.write("      </main>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../fix/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
